title: RDKit User Group Meeting 2020
description: >
  UGM JP 2020 has been cancelled due to the influence of COVID-19. We deeply apologize to everyone who was planning to participate in UGM JP 2020.
baseurl: "/UGMJP2020"
url: "https://rdkit-users-jp.github.io"

image: http://rdkit-users.jp/UGMJP2020/css/2017_style/img/logos/summary.png
logo: http://rdkit-users.jp/UGMJP2020/css/2017_style/img/logos/summary.png

include: ['_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
permalink: pretty
destination: ./build
